---
title: record_exception (PythonエージェントAPI)
type: apiDoc
shortDescription: Pythonの例外の詳細をエラーとして記録します。
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
translationType: machine
---

## 構文

```
newrelic.agent.record_exception(exc=None, value=None, tb=None, params={}, ignore_errors=[], application=None)
```

このAPIは廃止されました。 [`notice_error()`](/docs/agents/python-agent/python-agent-api/notice_error) をご利用ください。

## 説明

Pythonの例外の詳細をエラーとして記録します。

デフォルトでは、Python エージェントはハンドルされていない例外のみを報告します。 `record_exception` を使用すると、Python の例外をエラーとして記録し、New Relic One で確認することができます。パラメータが指定されていない場合は、現在処理されている例外の詳細が使用されます。

[トランザクションごとに最大5つの異なる例外を記録することができます。](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) また、 [ハーベストサイクルごとにすべてのトランザクションの合計で最大20の例外を記録することができます。](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle) 。

監視されているウェブリクエストやバックグラウンドタスクのコンテキスト内で `record_exception()` が呼び出されると、リクエストやタスクが報告されているアプリケーションに対して、例外の詳細が報告されます。

監視対象のウェブリクエストやバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`](/docs/agents/python-agent/python-agent-api/application) キーワード引数が提供され、例外を記録する必要のあるアプリケーションに対応するアプリケーションオブジェクトが提供されない限り、呼び出しは無視されます。適切なアプリケーション・オブジェクトは、 `newrelic.agent.application()` 関数を使って取得できます。

## パラメータ

<Callout variant="tip">
  ほとんどすべての場合、 `record_exception` はパラメータを必要としません。
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメーター
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `excuse`

        _クラスオブジェクト_
      </td>

      <td>
        オプションで、ほとんど使用されません。処理される例外の例外タイプ（クラスオブジェクト）です。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返される3つの値(`exc`, `value`, `tb`)のうちの1つです。これらのパラメータのいずれかを渡したい場合は、3つすべてを設定する必要があり、 `None` には設定できません。これらの値のうち1つだけを渡した場合、呼び出しは動作しません。
      </td>
    </tr>

    <tr>
      <td>
        `value`

        _整数、文字列、その他_
      </td>

      <td>
        オプションで、ほとんど使用されません。例外パラメータです。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返される3つの値(`exc`, `value`, `tb`)のうちの1つです。これらのパラメータのいずれかを渡したい場合は、3つすべてを設定する必要があり、 `None` には設定できません。これらの値のうち1つだけを渡した場合、呼び出しは動作しません。
      </td>
    </tr>

    <tr>
      <td>
        `tb`

        _オブジェクト_
      </td>

      <td>
        オプションで、ほとんど使用されません。例外が最初に発生した時点でのコールスタックをカプセル化したトレースバックオブジェクトです。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返される3つの値(`exc`, `value`, `tb`)のうちの1つです。これらのパラメータのいずれかを渡したい場合は、3つすべてを設定する必要があり、 `None` には設定できません。これらの値のうち1つだけを渡した場合、呼び出しは動作しません。
      </td>
    </tr>

    <tr>
      <td>
        `params`

        _ディクト_
      </td>

      <td>
        オプションです。エラーイベントに追加するカスタム属性（トランザクションに既に追加されているカスタム属性に加えて）。 [ハイセキュリティモード](/docs/agents/manage-apm-agents/configuration/high-security-mode) が有効になっている場合、これは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `ignore_errors`

        _文字列_
      </td>

      <td>
        オプションです。無視するエラーは `module:class` のような形で渡すことができます。特定のタイプの例外を常に無視し、記録しないようにする場合に便利です。
      </td>
    </tr>

    <tr>
      <td>
        `アプリケーション`

        _アプリケーションオブジェクト_
      </td>

      <td>
        オプションです。監視対象のウェブリクエストやバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`アプリケーション` オブジェクト](/docs/agents/python-agent/python-agent-api/application) が提供されない限り、呼び出しは無視されます。
      </td>
    </tr>
  </tbody>
</table>

## 戻り値

なし。

## 例

### 例外の報告の簡単な例 [#simple-example]

ほとんどの場合、パラメタを渡す必要はありません。例外を報告したい場合は、次のように呼び出せばよいでしょう。

```
newrelic.agent.record_exception()
```

### sys.exc_info()タプルと追加パラメータを用いたコール [#complex-example]

`record_exception` using `sys.exc_info()` data の例です。

```
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.record_exception(params={'my_special_exception': True}, ignore_errors=complex_ignore_errors)
```

### コールバックの使用例 [#callback-example]

特定の例外タイプの属性に基づいて例外を動的にフィルタリングする必要がある場合は、コールバック関数を指定できます。

```
def _ignore_errors(exc, value, tb): 
    if instance(value, HTTPError): 
        if value.status == 404: 
            return True

newrelic.agent.record_exception(ignore_errors=_ignore_errors)
```

例外を無視する場合は、callable の戻り値を `True` に設定します。他のチェックに関係なく例外を決して無視してはいけない場合は `False` を、その後のチェックや内蔵ルールで例外を無視すべきかどうかを判断すべき場合は `None` を返します。コールバックは通常、 `True` または `None` のいずれかを返します。
